/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.EndController;
import java.awt.Label;

/**
 * Dialog di akhir permainan.
 * @author Asus
 */
public class EndDialog extends javax.swing.JDialog {
  
  /*Controller dari End*/
  private EndController endController;
  /*Frame yang menjadi parent*/
  private MainFrame parent;
  
  /**
   * Konstruktor. 
   * @param parent komponen yang menjadi parent
   * @param modal modal
   */
  public EndDialog(MainFrame parent, boolean modal) {
    this.parent = parent;
    initComponents();
    score.setText("Score = " + parent.getScorePanel()
        .getDataController().getGameStateModel().getScore());
    endController = new EndController(this);
    this.setLocationRelativeTo(parent);
    this.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    gameOver = new java.awt.Label();
    score = new java.awt.Label();
    okButton = new javax.swing.JButton();
    highScore = new java.awt.Label();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    gameOver.setAlignment(java.awt.Label.CENTER);
    gameOver.setFont(new java.awt.Font("Dosis", 0, 18)); // NOI18N
    gameOver.setText("Rest In Peace");

    score.setAlignment(java.awt.Label.CENTER);
    score.setFont(new java.awt.Font("Dosis", 0, 14)); // NOI18N
    score.setName("score"); // NOI18N
    score.setText("Score");

    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });

    highScore.setAlignment(java.awt.Label.CENTER);
    highScore.setFont(new java.awt.Font("Dosis", 0, 14)); // NOI18N
    highScore.setName("score"); // NOI18N
    highScore.setText("High Score");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(gameOver, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        .addComponent(score, javax.swing.GroupLayout.DEFAULT_SIZE, 
        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 
        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
        .addComponent(highScore, javax.swing.GroupLayout.DEFAULT_SIZE, 
        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(gameOver, javax.swing.GroupLayout.PREFERRED_SIZE,
        40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 40, 
        javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(2, 2, 2)
        .addComponent(highScore, javax.swing.GroupLayout.PREFERRED_SIZE, 40, 
        javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 
        18, Short.MAX_VALUE)
        .addComponent(okButton)
        .addContainerGap())
    );

    pack();
  }
  // </editor-fold>//GEN-END:initComponents

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
    //GEN-FIRST:event_okButtonActionPerformed
    System.out.println("ok");
    System.exit(0);
  }
  //GEN-LAST:event_okButtonActionPerformed

  /**
   * Getter parent.
   * @return parent dari dialog ini
   */
  public MainFrame getParent() {
    return parent;
  }
  
  /**
   * Getter label score.
   * @return label score
   */
  public Label getScore() {
    return score;
  }
  
  /**
   * Getter label high score.
   * @return label high score
   */
  public Label getHighScore() {
    return highScore;
  }
  
  /**
   * Getter endController.
   * @return endController
   */
  public EndController getEndController() {
    return endController;
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private java.awt.Label gameOver;
  private java.awt.Label highScore;
  private javax.swing.JButton okButton;
  private java.awt.Label score;
  // End of variables declaration//GEN-END:variables
}
