/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.PlayerController;
import javax.swing.ImageIcon;

/**
 * Panel permainan.
 * Berisi pemain dan musuh.
 * Warna background dapat berubah-ubah.
 * @author Asus
 */
public class GamePanel extends javax.swing.JPanel {
  /*Controller untuk player*/
  private PlayerController playerController;
  
  /**
   * Konstruktor.
   */
  public GamePanel() {
    initComponents();
    player.setFocusable(true);
    playerController = new PlayerController(player);
    playerController.start();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    player = new javax.swing.JLabel();

    setBackground(new java.awt.Color(102, 255, 204));
    setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
    setMaximumSize(new java.awt.Dimension(714, 300));
    setMinimumSize(new java.awt.Dimension(714, 300));
    setName(""); // NOI18N
    setPreferredSize(new java.awt.Dimension(714, 300));
    setLayout(null);

    player.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/komodo.gif"))); // NOI18N
    player.setName("player"); // NOI18N
    player.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        playerKeyReleased(evt);
      }
    });
    add(player);
    player.setBounds(0, 222, 64, 78);

    getAccessibleContext().setAccessibleParent(this);
  }// </editor-fold>//GEN-END:initComponents

  private void playerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_playerKeyReleased
    if (!playerController.isStartJumping && evt.getExtendedKeyCode() == 38) {
      System.out.println("up");
      playerController.isStartJumping = true;
    }
  }//GEN-LAST:event_playerKeyReleased

  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel player;
  // End of variables declaration//GEN-END:variables
}
