/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 * Frame utama.
 * @author Asus
 */
public class MainFrame extends javax.swing.JFrame {

  /**
   * Konstruktor.
   */
  public MainFrame() {
    initComponents();
    settingComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    ground = new javax.swing.JPanel();
    gamePanel = new view.GamePanel();
    scorePanel1 = new view.ScorePanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Komodo Run");
    setBackground(new java.awt.Color(0, 0, 0));
    setName("mainFrame"); // NOI18N

    ground.setBackground(new java.awt.Color(153, 153, 0));
    ground.setAlignmentX(0.0F);
    ground.setAlignmentY(0.0F);
    ground.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    ground.setMaximumSize(new java.awt.Dimension(714, 36));
    ground.setMinimumSize(new java.awt.Dimension(714, 36));
    ground.setPreferredSize(new java.awt.Dimension(714, 36));

    javax.swing.GroupLayout groundLayout = new javax.swing.GroupLayout(ground);
    ground.setLayout(groundLayout);
    groundLayout.setHorizontalGroup(
      groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 714, Short.MAX_VALUE)
    );
    groundLayout.setVerticalGroup(
      groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 36, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout scorePanel1Layout = new javax.swing.GroupLayout(scorePanel1);
    scorePanel1.setLayout(scorePanel1Layout);
    scorePanel1Layout.setHorizontalGroup(
      scorePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 714, Short.MAX_VALUE)
    );
    scorePanel1Layout.setVerticalGroup(
      scorePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 50, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(gamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(scorePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(scorePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(gamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Setting tambahan untuk komponen.
   */
  private void settingComponents() {
    this.setResizable(false);
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private view.GamePanel gamePanel;
  private javax.swing.JPanel ground;
  private view.ScorePanel scorePanel1;
  // End of variables declaration//GEN-END:variables
}
