/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.StartController;
import javax.swing.JLabel;

/**
 * Menu di awal permainan.
 * @author Asus
 */
public class StartDialog extends javax.swing.JDialog {
  
  /*Controller dari Start*/
  private StartController startController;
  /*Frame yang menjadi parent*/
  private MainFrame parent;
  
  /**
   * Konstruktor.
   * @param parent komponen yang menjadi parent
   * @param modal modal
   */
  public StartDialog(MainFrame parent, boolean modal) {
    this.parent = parent;
    initComponents();
    startController = new StartController(this);
    this.setLocationRelativeTo(parent);
    this.setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    welcome = new javax.swing.JLabel();
    start = new javax.swing.JButton();
    highScore = new javax.swing.JButton();
    highScoreDisplay = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    welcome.setText("Welcome, Komodo");

    start.setText("Start Game");
    start.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        startActionPerformed(evt);
      }
    });

    highScore.setText("High Score");
    highScore.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        highScoreActionPerformed(evt);
      }
    });

    highScoreDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    highScoreDisplay.setText(" ");
    highScoreDisplay.setName("highScoreDisplay"); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(welcome, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
          .addComponent(highScoreDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing
            .GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
          .addContainerGap()
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(highScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing
            .GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing
            .GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
        .addComponent(welcome)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(start)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(highScore)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(highScoreDisplay))
    );

    pack();
  }
  // </editor-fold>//GEN-END:initComponents

  private void startActionPerformed(java.awt.event.ActionEvent evt) {
    //GEN-FIRST:event_startActionPerformed
    System.out.println("start");
    startController.startGame();
  }
  //GEN-LAST:event_startActionPerformed

  private void highScoreActionPerformed(java.awt.event.ActionEvent evt) {
    //GEN-FIRST:event_highScoreActionPerformed
    System.out.println("high");
    startController.displayHighScore();
  }
  //GEN-LAST:event_highScoreActionPerformed

  /**
   * Getter highScoreDisplay.
   * @return JLabel yang menampilkan high score
   */
  public JLabel getHighScoreDisplay() {
    return highScoreDisplay;
  }
  
  /**
   * Getter parent.
   * @return parent dari dialog ini
   */
  public MainFrame getParent() {
    return parent;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton highScore;
  private javax.swing.JLabel highScoreDisplay;
  private javax.swing.JButton start;
  private javax.swing.JLabel welcome;
  // End of variables declaration//GEN-END:variables
}
